module.exports = [
  {
    slug: "velvet-lip-souffle",
    name: "Velvet Lip Soufflé",
    brand: "AURÉLIA",
    category: "Makeup",
    price: 29,
    images: [
      "https://images.unsplash.com/photo-1526045478516-99145907023c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "Air-whipped pigment with a soft-focus finish. Blurs edges, never dries the lip.",
    shades: ["Nude Muse", "Rose Noir", "Crimson Silk", "Cocoa Kiss"],
    tags: ["lip", "velvet", "soft-matte"],
    isFeatured: true,
  },
  {
    slug: "glass-skin-radiance-serum",
    name: "Glass-Skin Radiance Serum",
    brand: "AURÉLIA",
    category: "Skincare",
    price: 54,
    images: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "Plumping hydration + light-bending glow for that ‘expensive skin’ look.",
    shades: ["Universal"],
    tags: ["serum", "glow", "hydration"],
    isFeatured: true,
  },
  {
    slug: "blush-veil-cloud-cream",
    name: "Blush Veil Cloud Cream",
    brand: "AURÉLIA",
    category: "Makeup",
    price: 34,
    images: [
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "A sheer-to-bold cream blush with a watercolor diffusion.",
    shades: ["Petal Dust", "Spiced Rose", "Soft Berry", "Warm Honey"],
    tags: ["blush", "cream", "veil"],
    isFeatured: true,
  },
  {
    slug: "satin-foundation-40",
    name: "Satin Foundation",
    brand: "AURÉLIA",
    category: "Makeup",
    price: 48,
    images: [
      "https://images.unsplash.com/photo-1512207847401-7e0e7f59d5f8?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "Breathable satin coverage that melts into skin and photographs beautifully.",
    shades: ["Light Neutral", "Medium Olive", "Tan Warm", "Deep Cool"],
    tags: ["foundation", "satin", "complexion"],
    isFeatured: true,
  },
  {
    slug: "golden-halo-highlighter",
    name: "Golden Halo Highlighter",
    brand: "AURÉLIA",
    category: "Makeup",
    price: 38,
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "A refined glow—no glitter, just light.",
    shades: ["Champagne", "Gold Nectar", "Bronze Beam"],
    tags: ["highlighter", "glow"],
  },
  {
    slug: "barrier-silk-moisturizer",
    name: "Barrier-Silk Moisturizer",
    brand: "AURÉLIA",
    category: "Skincare",
    price: 46,
    images: [
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "Velvet hydration that cushions skin and locks in dew.",
    shades: ["Universal"],
    tags: ["moisturizer", "barrier"],
  },
  {
    slug: "silk-rinse-hair-elixir",
    name: "Silk-Rinse Hair Elixir",
    brand: "AURÉLIA",
    category: "Haircare",
    price: 42,
    images: [
      "https://images.unsplash.com/photo-1526045478516-99145907023c?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "Weightless shine and slip for a glossy finish.",
    shades: ["Universal"],
    tags: ["hair", "shine"],
  },
  {
    slug: "vanilla-musk-eau",
    name: "Vanilla Musk Eau de Parfum",
    brand: "AURÉLIA",
    category: "Fragrance",
    price: 72,
    images: [
      "https://images.unsplash.com/photo-1500835556837-99ac94a94552?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1526045478516-99145907023c?auto=format&fit=crop&w=1400&q=80",
    ],
    description: "A soft skin scent: vanilla orchid, clean musk, and warm amber woods.",
    shades: ["50ml"],
    tags: ["fragrance", "musk", "vanilla"],
  },
];

